"""Add a human-friendly conversation code.

Revision ID: 010_add_conversation_code
Revises: 009_add_user_delivery_defaults
Create Date: 2026-07-09

Staff track conversations by a short code (``CT-YYYYMMDD-NNN``) instead of the raw
UUID ``session_id``. A trigger fills the code on insert, mirroring the orders
``generate_order_number`` scheme. The UUID id/session_id stay the internal keys.

Each statement is issued via its own ``op.execute()`` because asyncpg cannot run
multi-statement SQL in a single execute; dollar-quoted function bodies count as a
single statement and are fine.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "010_add_conversation_code"
down_revision: str | None = "009_add_user_delivery_defaults"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add the conversation code column, generator, trigger, and backfill."""
    op.execute("ALTER TABLE conversations ADD COLUMN code VARCHAR(20)")

    op.execute(
        """
        CREATE OR REPLACE FUNCTION generate_conversation_code()
        RETURNS VARCHAR AS $$
        DECLARE
            new_code VARCHAR;
            today_date VARCHAR;
            counter INTEGER;
        BEGIN
            today_date := TO_CHAR(NOW(), 'YYYYMMDD');
            SELECT COALESCE(MAX(CAST(SUBSTRING(code FROM 13) AS INTEGER)), 0) + 1
            INTO counter
            FROM conversations
            WHERE code LIKE 'CT-' || today_date || '-%';
            new_code := 'CT-' || today_date || '-' || LPAD(counter::TEXT, 3, '0');
            RETURN new_code;
        END;
        $$ LANGUAGE plpgsql
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_conversation_code()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.code IS NULL OR NEW.code = '' THEN
                NEW.code := generate_conversation_code();
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )

    op.execute(
        """
        CREATE TRIGGER trigger_set_conversation_code
            BEFORE INSERT ON conversations
            FOR EACH ROW
            EXECUTE FUNCTION set_conversation_code()
        """
    )

    op.execute(
        """
        UPDATE conversations AS c
        SET code = 'CT-'
            || TO_CHAR(c.created_at, 'YYYYMMDD')
            || '-'
            || LPAD(sub.rn::TEXT, 3, '0')
        FROM (
            SELECT id, ROW_NUMBER() OVER (
                PARTITION BY TO_CHAR(created_at, 'YYYYMMDD')
                ORDER BY created_at, id
            ) AS rn
            FROM conversations
        ) AS sub
        WHERE c.id = sub.id AND c.code IS NULL
        """
    )

    op.execute("CREATE UNIQUE INDEX idx_conversations_code ON conversations(code)")
    op.execute(
        "COMMENT ON COLUMN conversations.code IS "
        "'Format: CT-YYYYMMDD-NNN, auto-generated by trigger'"
    )


def downgrade() -> None:
    """Drop the conversation code column, generator, and trigger."""
    op.execute("DROP TRIGGER IF EXISTS trigger_set_conversation_code ON conversations")
    op.execute("DROP FUNCTION IF EXISTS set_conversation_code()")
    op.execute("DROP FUNCTION IF EXISTS generate_conversation_code()")
    op.execute("DROP INDEX IF EXISTS idx_conversations_code")
    op.execute("ALTER TABLE conversations DROP COLUMN IF EXISTS code")
